### ISSUE TITLE
Projeto entregue

### ISSUE THREAD

**Issue by julio-lemos** [mateusavila/dev-hall-front-end-1#1]
Boa noite.

Segue link de repositório com projeto: https://github.com/julio-lemos/dev-hall-front-end-1
Link do deploy: https://dev-hall-front-end-1-ten.vercel.app/

Grato pelo desafio.

**Comment by mateusavila** [comment]
Oi Júlio

Tens como me mandar um e-mail para eu te enviar a tua avaliação?
